// Return Guard dashboard logic.
// All numbers come from RETURN_GUARD_DATA (data.js), which is generated by
// ml/train_model.py from real held-out test-set predictions. Nothing here
// invents a metric — the slider just looks up the precomputed sweep row
// closest to the chosen threshold.
//
// Resilience note: every DOM-rendering section below runs independently.
// Chart.js is loaded from a local vendored file (chart.umd.min.js) rather
// than a CDN, and both chart calls are wrapped in try/catch, so a charting
// failure can never blank out the queue, the health numbers, or anything
// else on the page.

const DATA = RETURN_GUARD_DATA;
const CURRENCY = DATA.metrics.assumptions.currency === "INR" ? "\u20B9" : "$";
const decisions = {}; // order_id -> chosen decision (in-memory only, resets on reload)

function fmtMoney(n) {
  const sign = n < 0 ? "\u2212" : "";
  return `${sign}${CURRENCY}${Math.abs(Math.round(n)).toLocaleString("en-IN")}`;
}
function fmtPct(n) { return `${Math.round(n * 100)}%`; }

function nearestSweepRow(threshold) {
  let best = DATA.sweep[0];
  let bestDiff = Infinity;
  for (const row of DATA.sweep) {
    const diff = Math.abs(row.threshold - threshold);
    if (diff < bestDiff) { bestDiff = diff; best = row; }
  }
  return best;
}

// ================= Tabs =================
document.querySelectorAll(".tab").forEach(btn => {
  btn.addEventListener("click", () => {
    document.querySelectorAll(".tab").forEach(b => { b.classList.remove("active"); b.setAttribute("aria-selected", "false"); });
    document.querySelectorAll(".panel").forEach(p => p.classList.remove("active"));
    btn.classList.add("active");
    btn.setAttribute("aria-selected", "true");
    document.getElementById(`panel-${btn.dataset.tab}`).classList.add("active");
  });
});

// ================= Header meta =================
document.getElementById("test-set-size").textContent = DATA.metrics.n_test.toLocaleString("en-IN");

// ================= Impact Simulator (numbers only, no chart) =================
const slider = document.getElementById("threshold-slider");
slider.value = DATA.metrics.default_threshold;

function renderSimulator(threshold) {
  const row = nearestSweepRow(threshold);
  document.getElementById("threshold-readout").textContent = fmtPct(row.threshold);

  const heroEl = document.getElementById("hero-net-impact");
  heroEl.textContent = fmtMoney(row.net_impact);
  heroEl.classList.toggle("negative", row.net_impact < 0);

  document.getElementById("stat-precision").textContent = fmtPct(row.precision);
  document.getElementById("stat-recall").textContent = fmtPct(row.recall);
  document.getElementById("stat-f1").textContent = row.f1.toFixed(2);
  document.getElementById("stat-flagged").textContent = (row.tp + row.fp).toLocaleString("en-IN");
  document.getElementById("stat-flagged-total").textContent = DATA.metrics.n_test.toLocaleString("en-IN");

  document.getElementById("impact-prevented").textContent = fmtMoney(row.loss_prevented);
  document.getElementById("impact-fp").textContent = "\u2212" + fmtMoney(row.fp_friction_cost);
  document.getElementById("impact-review").textContent = "\u2212" + fmtMoney(row.review_cost);
  document.getElementById("impact-missed").textContent = fmtMoney(row.loss_missed);

  if (window.curveChart) {
    try {
      window.curveChart.data.datasets[1].data = [{ x: row.threshold, y: row.net_impact }];
      window.curveChart.update("none");
    } catch (e) { console.warn("Curve chart update skipped:", e); }
  }
}

slider.addEventListener("input", () => renderSimulator(parseFloat(slider.value)));
renderSimulator(parseFloat(slider.value));

// ================= Assumptions =================
const A = DATA.metrics.assumptions;
document.getElementById("assumptions-grid").innerHTML = `
  <div class="assumption-item"><div class="a-label">Cost of a missed/caught return</div><div class="a-value">${Math.round(A.return_loss_fraction * 100)}% of order value</div></div>
  <div class="assumption-item"><div class="a-label">False-positive friction cost</div><div class="a-value">${Math.round(A.false_positive_friction_fraction * 100)}% of order value</div></div>
  <div class="assumption-item"><div class="a-label">Manual review cost</div><div class="a-value">${fmtMoney(A.flat_review_cost)} / order</div></div>
  <div class="assumption-item"><div class="a-label">Currency</div><div class="a-value">${A.currency}</div></div>
`;

// ================= Risk Queue =================
let activeBand = "ALL";

function orderRowHTML(o) {
  const chosen = decisions[o.order_id];
  const factorsHTML = o.top_factors.map(f => {
    const width = Math.min(100, Math.abs(f.impact) * 40 + 15);
    return `
      <div class="factor-item">
        <span class="factor-name">${f.feature}</span>
        <span class="factor-bar-track"><span class="factor-bar-fill ${f.direction}" style="width:${width}%"></span></span>
      </div>`;
  }).join("");

  return `
    <div class="order-row" data-band="${o.risk_band}" data-order-id="${o.order_id}">
      <div class="order-row-main">
        <div class="order-id">#${o.order_id}</div>
        <div class="order-primary">
          <div class="order-category">${o.category}</div>
          <div class="order-sub">Customer #${o.customer_id} · ${o.payment_method}</div>
        </div>
        <div class="order-value-cell"><span class="cell-label">Order value</span>${CURRENCY}${Math.round(o.order_value).toLocaleString("en-IN")}</div>
        <div class="order-value-cell"><span class="cell-label">Prior return rate</span>${Math.round(o.prior_return_ratio * 100)}%</div>
        <span class="risk-pill band-${o.risk_band}"><span class="pill-dot"></span>${o.risk_score}</span>
        <span class="chevron">›</span>
      </div>
      <div class="order-detail">
        <div class="detail-columns">
          <div>
            <div class="decision-label">Why this score — top SHAP drivers</div>
            <div class="factor-list">${factorsHTML}</div>
          </div>
          <div>
            <div class="decision-label">Merchant decision</div>
            <div class="decision-buttons">
              <button class="decision-btn ${chosen === "Approve" ? "chosen" : ""}" data-decision="Approve">Approve</button>
              <button class="decision-btn ${chosen === "Verify" ? "chosen" : ""}" data-decision="Verify">Ask for verification</button>
              <button class="decision-btn ${chosen === "Hold" ? "chosen" : ""}" data-decision="Hold">Hold for review</button>
            </div>
            <div class="logged-note">${chosen ? `Logged: ${chosen} — order #${o.order_id}` : "No decision recorded yet. Choices are stored in this session only."}</div>
          </div>
        </div>
      </div>
    </div>`;
}

function renderQueue() {
  const list = document.getElementById("queue-list");
  const rows = DATA.orders.filter(o => activeBand === "ALL" || o.risk_band === activeBand);
  list.innerHTML = rows.map(o => orderRowHTML(o)).join("");

  list.querySelectorAll(".order-row").forEach(rowEl => {
    rowEl.addEventListener("click", (e) => {
      if (e.target.closest(".decision-btn")) return;
      rowEl.classList.toggle("expanded");
    });
    rowEl.querySelectorAll(".decision-btn").forEach(btn => {
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        const orderId = rowEl.dataset.orderId;
        decisions[orderId] = btn.dataset.decision;
        rowEl.querySelectorAll(".decision-btn").forEach(b => b.classList.remove("chosen"));
        btn.classList.add("chosen");
        const note = rowEl.querySelector(".logged-note");
        if (note) note.textContent = `Logged: ${btn.dataset.decision} — order #${orderId}`;
      });
    });
  });
}

document.querySelectorAll(".band-chip").forEach(chip => {
  chip.addEventListener("click", () => {
    document.querySelectorAll(".band-chip").forEach(c => c.classList.remove("active"));
    chip.classList.add("active");
    activeBand = chip.dataset.band;
    renderQueue();
  });
});

renderQueue();

// ================= Model Health (text + confusion matrix, no chart) =================
const M = DATA.metrics;
document.getElementById("health-split").textContent = `${M.n_train.toLocaleString("en-IN")} / ${M.n_test.toLocaleString("en-IN")}`;
document.getElementById("health-auc").textContent = M.roc_auc.toFixed(3);
document.getElementById("health-base-rate").textContent = fmtPct(M.test_return_rate);
document.getElementById("health-threshold").textContent = fmtPct(M.default_threshold);

const defaultRow = nearestSweepRow(M.default_threshold);
document.getElementById("confusion-matrix").innerHTML = `
  <div class="cm-cell cm-head"></div>
  <div class="cm-cell cm-head">Predicted: return</div>
  <div class="cm-cell cm-head">Predicted: no return</div>

  <div class="cm-cell cm-head">Actual: return</div>
  <div class="cm-cell cm-correct"><div class="cm-num">${defaultRow.tp}</div><div class="cm-tag">true positive</div></div>
  <div class="cm-cell cm-wrong"><div class="cm-num">${defaultRow.fn}</div><div class="cm-tag">false negative (missed)</div></div>

  <div class="cm-cell cm-head">Actual: no return</div>
  <div class="cm-cell cm-wrong"><div class="cm-num">${defaultRow.fp}</div><div class="cm-tag">false positive</div></div>
  <div class="cm-cell cm-correct"><div class="cm-num">${defaultRow.tn}</div><div class="cm-tag">true negative</div></div>
`;

// ================= Charts (isolated — failures here can't affect anything above) =================
try {
  if (typeof Chart === "undefined") throw new Error("Chart.js did not load (chart.umd.min.js missing or blocked)");

  const ctx = document.getElementById("curve-chart").getContext("2d");
  window.curveChart = new Chart(ctx, {
    type: "line",
    data: {
      datasets: [
        {
          label: "Net impact",
          data: DATA.sweep.map(r => ({ x: r.threshold, y: r.net_impact })),
          borderColor: "#5b8def",
          backgroundColor: "rgba(91,141,239,0.08)",
          borderWidth: 2,
          pointRadius: 0,
          fill: true,
          tension: 0.25,
        },
        {
          label: "Current threshold",
          data: [{ x: parseFloat(slider.value), y: nearestSweepRow(parseFloat(slider.value)).net_impact }],
          type: "scatter",
          backgroundColor: "#eaedf3",
          borderColor: "#12161c",
          borderWidth: 2,
          pointRadius: 6,
          pointHoverRadius: 7,
        },
      ],
    },
    options: {
      responsive: true,
      interaction: { intersect: false },
      plugins: { legend: { display: false } },
      scales: {
        x: {
          type: "linear",
          min: 0.05, max: 0.95,
          ticks: { color: "#8b95a8", callback: v => Math.round(v * 100) + "%" },
          grid: { color: "#232a36" },
          title: { display: true, text: "Threshold", color: "#8b95a8" },
        },
        y: {
          ticks: { color: "#8b95a8", callback: v => (v / 1000).toFixed(0) + "k" },
          grid: { color: "#232a36" },
          title: { display: true, text: `Net impact (${CURRENCY})`, color: "#8b95a8" },
        },
      },
    },
  });
} catch (e) {
  console.warn("Net-impact curve chart could not render:", e);
  const el = document.getElementById("curve-chart");
  if (el) el.outerHTML = `<p class="muted">Chart unavailable (${e.message}). The numbers above are still live and correct.</p>`;
}

try {
  if (typeof Chart === "undefined") throw new Error("Chart.js did not load (chart.umd.min.js missing or blocked)");

  const impCtx = document.getElementById("importance-chart").getContext("2d");
  const topImp = DATA.feature_importance.slice(0, 8);
  new Chart(impCtx, {
    type: "bar",
    data: {
      labels: topImp.map(f => f.feature),
      datasets: [{
        data: topImp.map(f => f.importance),
        backgroundColor: "#5b8def",
        borderRadius: 4,
        barThickness: 16,
      }],
    },
    options: {
      indexAxis: "y",
      responsive: true,
      plugins: { legend: { display: false } },
      scales: {
        x: { ticks: { color: "#8b95a8" }, grid: { color: "#232a36" } },
        y: { ticks: { color: "#c3c9d4", font: { size: 11 } }, grid: { display: false } },
      },
    },
  });
} catch (e) {
  console.warn("Feature importance chart could not render:", e);
  const el = document.getElementById("importance-chart");
  if (el) el.outerHTML = `<p class="muted">Chart unavailable (${e.message}).</p>`;
}
